### ISSUE TITLE
does it work?

### ISSUE THREAD

**Issue by neopaf** [detunized/seene-viewer#2]
Looks like I'm missing the point.
I expected the sample output to display something with 3D feeling from test camera.
yet I get regular structure all over the field
![2015-03-17 0 25 29](https://cloud.githubusercontent.com/assets/4362564/6676860/24d1c348-cc3c-11e4-9082-3ac58e7406a2.png)

Am investingating an idea to push these guys to consider printing Seene....
http://3d-crystals.ru/order/
https://imaage.com.au/3D-Crystal/3D-photocrystals

(not affiliated with any of these parties, nor with Seene itself, just a user)

Awing at your reverse engineering patience!

**Comment by detunized** [comment]
Hey, thanks!

It does work. The problem is there was no way to control the camera so it looked like nothing. I added mouse camera controls. You should be able to rotate, zoom and pan to explore the scene.

Make sure you run local HTTP server not just opening `index.html` in the browser. I wouldn't work with Chrome (it might with Firefox). I use `python -m SimpleHTTPServer`. Easy peasy.

**Comment by neopaf** [comment]
Thanks, a lot! (Спасибо!)

I've just published a small backup script. 
https://github.com/neopaf/seene-backup/blob/master/README.md
